### ISSUE TITLE
Spotify and sp command Bug

### ISSUE THREAD

**Issue by ShayanPXT** [fow5040/Flow.Launcher.Plugin.SpotifyPremium#18] opened 2023-02-13 03:35 UTC
### Issue Description

when I'm trying to use sp command to play Spotify I got this error: Flow Launcher got an error 

Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.22623.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 02/13/2023 07:00:54
Exception:
SpotifyPremium Exception: 
Websites: https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium
Author: Frank W. (@fow5040)
Version: 1.1.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Exception of type 'SpotifyAPI.Web.APIException' was thrown.
 ---> SpotifyAPI.Web.APIException: Exception of type 'SpotifyAPI.Web.APIException' was thrown.
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.ConnectWebClient(Boolean keepRefreshToken) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 263
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.ReconnectAsync(Boolean keepRefreshToken) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 519
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.QueryAsync(Query query, CancellationToken token) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 101
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 811
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 785
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Functionality Affected

Please mark the functionality of the plugin that is affected by the issue:

- [ ] Controlling the local Spotify client (changing track, pausing, skipping, muting)
- [ ] Searching Spotify for albums, artists, or songs

### Software Versions

Please fill in the following information:

- Spotify client version (`Help > About Spotify`): Spotify for Windows 1.2.4.912.g949d5fd0
- Flow Launcher version (`Flow Settings > About`): 1.13.0
[2023-02-13.txt](https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium/files/10718380/2023-02-13.txt)

**Please also make sure you're running the latest version of Flow.Launcher.Plugin.SpotifyPremium**

**Comment by fow5040** [comment] 2023-03-04 19:22
Is this still occurring? Was this transient? It's hard to tell from the Stack trace but I'm willing to bet it was either a temporary issue or one that can be resolved by examining the token file

**Comment by fow5040** [comment] 2023-08-03 15:46
Closing due to inactivity and lack of reproducibility

**Closed by fow5040** 2023-08-03 15:46 UTC
